name: Daily Commit Automation

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 05:30 UTC
  workflow_dispatch:       # Optional: lets you run manually

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add update by 23f2000804@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily update: $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push
